{
    "name": "OAK Sales Order Pool",
    "version": "16.0.1.0.0",
    "category": "Burr Oak",
    "license": "AGPL-3",
    "summary": "Sales - field additions ",
    "author": "Burr Oak Tool, Open Source Integrators",
    "website": "https://www.burroak.com",
    "maintainers": ["boti"],
    "depends": [
        "oak_sale",
        "base_automation",
        "sale",
        "account",
        "analytic",
    ],
    "data": [
        "security/oak_sale_security.xml",
        "security/ir.model.access.csv",
        "data/automation_data.xml",
        "views/sale_order.xml",
        "views/sale_type_account.xml",
        "views/analytic_account_views.xml",
    ],
    "demo": [],
    "qweb": [],
    "installable": True,
    "application": False,
    "auto_install": True,
}
