# Do NOT update manually; changes here will be overwritten by Copier
_commit: v1.14.2
_src_path: https://github.com/OCA/oca-addons-repo-template.git
ci: GitHub
dependency_installation_mode: PIP
generate_requirements_txt: true
github_check_license: false
github_ci_extra_env: {}
github_enable_codecov: true
github_enable_makepot: false
github_enable_stale_action: false
github_enforce_dev_status_compatibility: false
include_wkhtmltopdf: false
odoo_version: 16.0
org_name: Burr Oak Inc.
org_slug: burroaktoolinc
rebel_module_groups: []
repo_description: null
repo_name: Burr Oak Odoo 16
repo_slug: odoo-16
repo_website: https://github.com/burroaktoolinc/odoo-16
travis_apt_packages: []
travis_apt_sources: []

