{
    "name": "OAK Sales Additions",
    "version": "14.0.1.0.2",
    "category": "Burr Oak",
    "license": "AGPL-3",
    "summary": "Sales - Partner field additions",
    "author": "Burr Oak Tool, Open Source Integrators",
    "website": "https://www.burroak.com",
    "maintainers": ["emsmith"],
    "depends": [
        "base",
        "sale",
    ],
    "data": [
        "security/oak_sale_security.xml",
        "security/ir.model.access.csv",
        "report/sale_report.xml",
        "report/sale_work_report_templates.xml",
        "views/sales.xml",
        "views/sale_leadtime_message.xml",
        "views/css_template.xml",
        "views/blanket_order_views.xml",
        "views/stock_picking_view.xml",
    ],
    "demo": [],
    "qweb": [],
    "installable": True,
    "application": False,
    "auto_install": True,
}
