# Copyright (c) OpenValue All Rights Reserved

{
    "name": "MRP Planning Engine",
    "summary": "MRP Planning Engine",
    "version": "16.0.1.0",
    "category": "Manufacturing",
    "website": "www.openvalue.cloud",
    "author": "OpenValue",
    "support": "info@openvalue.cloud",
    "license": "Other proprietary",
    "price": 8000.00,
    "currency": "EUR",
    "depends": [
        "mrp_subcontracting",
        "purchase_stock",
        "mrp_shop_floor_control",
    ],
    "data": [
        "security/mrp_planning_engine_security.xml",
        "security/ir.model.access.csv",
        "data/mrp_planned_order_sequence.xml",
        "data/ir_cron.xml",
        "data/ir_actions_server.xml",
        "views/res_config_settings_views.xml",
        "views/stock_location_views.xml",
        "views/product_product_views.xml",
        "views/mrp_parameter_views.xml",
        "views/mrp_element_views.xml",
        "views/mrp_planned_order_views.xml",
        "views/mrp_planning_volume_views.xml",
        "views/mrp_production_views.xml",
        "views/purchase_order_views.xml",
        "views/sale_order_views.xml",
        "views/mrp_demand_views.xml",
        # "views/stock_warehouse_views.xml",
        "wizards/mrp_planning_engine_run_views.xml",
        "wizards/mrp_planning_engine_list_views.xml",
        "wizards/mrp_planning_engine_message_views.xml",
        "wizards/mrp_demand_massive_create_views.xml",
        "wizards/mrp_demand_adjustment_views.xml",
        "wizards/mrp_planning_engine_single_run_views.xml",
        "views/mrp_planning_engine_menu_views.xml",
    ],
    "application": True,
    "installable": True,
    "auto_install": False,
    "images": ["static/description/banner.png"],
}
