{
    "name": "OAK Helpdesk Documents",
    "version": "16.0.1.0.0",
    "category": "Burr Oak",
    "author": "Burr Oak Tool, Open Source Integrators",
    "website": "https://www.burroak.com",
    "license": "AGPL-3",
    "summary": "Helpdesk Documents Saved in a Centralized Location",
    "maintainers": ["Burr Oak Tool"],
    "depends": ["documents", "helpdesk"],
    "data": ["data/documents_helpdesk_data.xml", "views/documents_views.xml"],
    "installable": True,
    "application": False,
    "auto_install": False,
}
