{
    "name": "OAK Field Service Additions",
    "version": "16.0.1.0.0",
    "category": "Burr Oak",
    "author": "Burr Oak Tool, Open Source Integrators",
    "website": "https://www.burroak.com",
    "license": "AGPL-3",
    "summary": "Field Service additions",
    "maintainers": ["Burr Oak Tool"],
    "depends": [
        "project",
        "project_timeline",
        "project_template",
        "project_list",
        "industry_fsm",
        "industry_fsm_forecast",
        "industry_fsm_report",
        "industry_fsm_sale",
        "industry_fsm_sale_report",
        "industry_fsm_stock",
    ],
    "data": [
        "data/customer_service_worksheet.xml",
        "data/service_req_worksheet.xml",
        "report/customer_service_report_internal.xml",
        "report/customer_service_report_external.xml",
        "report/service_req_report.xml",
    ],
    "installable": True,
    "application": False,
    "auto_install": False,
}
