{
    "name": "OAK Helpdesk to ECO",
    "version": "16.0.1.0.0",
    "category": "Burr Oak",
    "author": "Burr Oak Tool, Open Source Integrators",
    "website": "https://www.burroak.com",
    "license": "AGPL-3",
    "summary": "Create ECO from Helpdesk Ticket",
    "maintainers": ["Burr Oak Tool"],
    "depends": ["helpdesk", "mrp_plm"],
    "data": [
        "security/ir.model.access.csv",
        "views/helpdesk_views.xml",
        "views/plm_eco_views.xml",
        "wizard/create_eco_views.xml",
    ],
    "demo": [],
    "qweb": [],
    "installable": True,
    "auto_install": False,
}
